# Generated by Django 6.0.2 on 2026-03-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_of_facts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='model',
        ),
    ]
