# Generated by Django 6.0.2 on 2026-03-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_of_facts', '0002_rename_brand_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('birth_date', models.DateField()),
                ('experience', models.PositiveIntegerField()),
                ('license', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_of_facts.car')),
            ],
        ),
    ]
